export const corpus: string[] = [
  "William Shakespeare was an English playwright, widely regarded as the greatest writer in the English language.",
  "The town of Stratford-upon-Avon lies on the River Avon approximately one hundred and one miles northwest of London.",
  "During the Elizabethan era, the Globe Theatre became a centre for dramatic performance in London.",
  "The Andromeda Galaxy is approximately two and a half million light years from Earth and is on a collision course with the Milky Way.",
  "Quantum mechanics describes physical phenomena at nanoscopic scales where the action is on the order of Planck's constant.",
  "The Industrial Revolution began in Great Britain and marked a major turning point in history, affecting almost every aspect of daily life.",
  "Mount Everest, on the border of Nepal and China, is the Earth's highest mountain above sea level.",
  "The human genome consists of approximately three billion base pairs organised into twenty three chromosome pairs.",
  "Photosynthesis converts light energy into chemical energy, producing glucose and releasing oxygen as a by-product.",
  "The speed of light in vacuum is approximately two hundred and ninety nine thousand seven hundred and ninety two kilometres per second.",
  "The Roman Empire reached its greatest territorial extent under Trajan in the second century of the common era.",
  "The city of Alexandria in Egypt was a renowned centre of Hellenistic scholarship and culture.",
  "A black hole is a region of spacetime where gravity is so strong that nothing, not even light, can escape.",
  "The Great Barrier Reef off the coast of Queensland, Australia, is the world's largest coral reef system.",
  "The French Revolution profoundly altered the course of modern history, leading to the rise of Napoleon Bonaparte.",
  "RNA acts as a messenger carrying instructions from DNA for controlling the synthesis of proteins.",
  "The Sahara Desert is the largest hot desert in the world, spanning multiple countries in North Africa.",
  "The theory of plate tectonics explains the movement of Earth's lithospheric plates and the occurrence of earthquakes and volcanoes.",
  "In 1609, Galileo Galilei improved the telescope and made astronomical observations that supported heliocentrism.",
  "The Silk Road connected the East and West, facilitating trade and cultural exchange across Eurasia.",
  "In computing, a central processing unit executes instructions of a computer program by performing basic arithmetic, logic, control, and input/output operations.",
  "The city of Kyoto in Japan is famous for its classical Buddhist temples, gardens, imperial palaces, and traditional wooden houses.",
  "The Amazon rainforest contains unparalleled biodiversity and plays a crucial role in the global carbon cycle.",
  "Magnetic resonance imaging uses strong magnetic fields and radio waves to generate images of organs in the body.",
  "The Renaissance was a period in European history marking the transition from the Middle Ages to modernity.",
  "Euclidean geometry studies plane and solid figures based on axioms and theorems employed by the Greek mathematician Euclid.",
  "The periodic table arranges chemical elements in order of increasing atomic number, highlighting periodic trends.",
  "The city of Timbuktu was an important centre of trade and Islamic scholarship in West Africa.",
  "In statistics, the normal distribution is a continuous probability distribution that is symmetric about the mean.",
  "The Wright brothers achieved the first controlled, sustained flight of a powered aircraft in 1903 at Kitty Hawk, North Carolina.",
  "The Mariana Trench in the western Pacific Ocean is the deepest oceanic trench on Earth.",
  "In literature, stream of consciousness is a narrative method that depicts the flow of thoughts and feelings in a character's mind.",
  "The Fibonacci sequence is a series of numbers in which each number is the sum of the two preceding ones.",
  "The printing press, invented by Johannes Gutenberg, revolutionised the spread of information in Europe.",
  "General relativity, proposed by Albert Einstein, describes gravity as the curvature of spacetime caused by mass and energy.",
  "The Taj Mahal in Agra, India, is an ivory-white marble mausoleum built by Mughal emperor Shah Jahan.",
  "The city of Cusco in Peru was the historic capital of the Inca Empire.",
  "The Louvre Museum in Paris houses thousands of works of art, including the Mona Lisa and the Venus de Milo.",
  "The Great Wall of China is a series of fortifications built across the historical northern borders of ancient Chinese states.",
  "In biology, mitochondria are organelles known as the powerhouses of the cell because they generate most of the cell's ATP.",
  "The phenomenon of superconductivity involves zero electrical resistance and expulsion of magnetic fields occurring in certain materials at low temperatures.",
  "The city of Venice is built on more than one hundred small islands in a lagoon in the Adriatic Sea.",
  "In economics, supply and demand determine prices in a competitive market under idealised assumptions.",
  "The Hubble Space Telescope has provided deep-field images that have expanded our understanding of the universe's structure.",
  "The city of Istanbul, historically known as Byzantium and Constantinople, straddles Europe and Asia across the Bosporus Strait.",
  "In cryptography, public-key systems allow secure communication without the need to share a secret key in advance.",
  "The Mona Lisa is a half-length portrait painting by the Italian artist Leonardo da Vinci, believed to depict Lisa Gherardini.",
  "The Colosseum in Rome is an oval amphitheatre that hosted gladiatorial contests and public spectacles in ancient times.",
  "The city of Reykjavik in Iceland is powered largely by geothermal energy, reducing reliance on fossil fuels.",
  "The human brain contains approximately eighty-six billion neurons interconnected through trillions of synapses.",
  "The Great Library of Alexandria was one of the largest and most significant libraries of the ancient world.",
  "Photosynthesis in plants occurs primarily in chloroplasts, organelles containing the green pigment chlorophyll.",
  "The city of Prague in the Czech Republic is renowned for its stunning medieval architecture and historic bridges.",
  "DNA replication is a biological process that occurs in all living organisms and is the basis for biological inheritance.",
  "The Aurora Borealis, or Northern Lights, is caused by the interaction of solar particles with Earth's magnetic field.",
  "The city of Barcelona is famous for the architectural works of Antoni Gaudí, including the Sagrada Família basilica.",
  "Artificial intelligence encompasses machine learning, natural language processing, and computer vision technologies.",
  "The Pacific Ring of Fire is a region around the Pacific Ocean where many earthquakes and volcanic eruptions occur.",
  "The city of Cairo is home to the Great Pyramid of Giza, one of the Seven Wonders of the Ancient World.",
  "Quantum entanglement is a physical phenomenon where particles become correlated in such a way that the quantum state of each particle cannot be described independently.",
  "The city of Vienna in Austria is celebrated for its musical heritage and was home to composers like Mozart and Beethoven.",
  "The immune system protects the body against infectious diseases and foreign substances through various defence mechanisms.",
  "The city of Mumbai is the financial capital of India and home to the Bollywood film industry.",
  "Climate change refers to long-term shifts in global temperatures and weather patterns caused by human activities.",
  "The city of Stockholm is built on fourteen islands connected by over fifty bridges in the Baltic Sea archipelago.",
  "Cryptocurrency is a digital currency secured by cryptography, making it nearly impossible to counterfeit or double-spend.",
  "The city of Athens is considered the birthplace of democracy and Western philosophy.",
  "The theory of evolution by natural selection explains how species change over time through genetic variation and environmental pressures.",
  "The city of Tokyo is the most populous metropolitan area in the world with over thirty-seven million inhabitants.",
  "Black holes are formed when massive stars collapse under their own gravity at the end of their life cycle.",
  "The city of Florence was the birthplace of the Renaissance and home to artists like Leonardo da Vinci and Michelangelo.",
  "The periodic table was first proposed by Dmitri Mendeleev in 1869 to organise chemical elements by atomic weight.",
  "The city of Sydney is famous for its iconic Opera House and Harbour Bridge spanning Port Jackson.",
  "Antibiotics are medicines that fight bacterial infections by either killing bacteria or inhibiting their growth.",
  "The city of Edinburgh is the capital of Scotland and hosts the world's largest arts festival every August.",
  "The Higgs boson is a fundamental particle that gives mass to other particles through the Higgs mechanism.",
  "The city of Marrakech in Morocco is known for its vibrant souks, palaces, and gardens in the Atlas Mountains.",
  "Renewable energy sources include solar, wind, hydroelectric, and geothermal power that naturally replenish over time.",
  "The city of Amsterdam is built on a network of canals and is famous for its narrow houses and cycling culture.",
  "The human circulatory system consists of the heart, blood vessels, and blood that transport nutrients throughout the body.",
  "The city of Buenos Aires is the capital of Argentina and the birthplace of the tango dance.",
  "Nanotechnology involves the manipulation of matter at the atomic and molecular scale to create new materials and devices.",
  "The city of Lisbon is built on seven hills overlooking the Tagus River and the Atlantic Ocean.",
  "The respiratory system enables gas exchange between the blood and the environment through the lungs and airways.",
  "The city of Dublin is the cultural and economic centre of Ireland, famous for its literary heritage and traditional music.",
  "Machine learning is a subset of artificial intelligence that enables computers to learn without explicit programming.",
  "The city of Brussels serves as the de facto capital of the European Union and hosts major EU institutions.",
  "The nervous system coordinates actions and sensory information by transmitting signals between different parts of the body.",
  "The city of Zurich is a global financial centre and consistently ranks among the world's most liveable cities.",
  "Genetic engineering involves the direct manipulation of genes using biotechnology to alter the characteristics of organisms.",
  "The city of Moscow is the largest city in Europe and the political and economic centre of Russia.",
  "The endocrine system regulates bodily functions through hormones produced by glands throughout the body.",
  "The city of Cape Town is situated at the foot of Table Mountain and is known for its natural beauty and wine regions.",
  "Blockchain technology provides a decentralised and secure way to record transactions across multiple computers.",
  "The city of Jerusalem is considered sacred by Judaism, Christianity, and Islam and has been continuously inhabited for millennia.",
  "The skeletal system provides structure, protects organs, and enables movement through joints and muscle attachments.",
  "The city of Bangkok is the capital of Thailand and famous for its ornate temples and bustling street markets.",
  "Virtual reality creates immersive digital environments that can simulate physical presence in real or imagined worlds.",
  "The city of Rio de Janeiro is famous for its beaches, Carnival festival, and the Christ the Redeemer statue.",
  "The digestive system breaks down food into nutrients that can be absorbed and used by the body for energy and growth.",
  "The city of Singapore is a city-state known for its efficient government, diverse culture, and strategic location in Southeast Asia.",
  "Biotechnology applies biological systems and organisms to develop products and technologies for various industries.",
  "The city of Tel Aviv is Israel's economic and technological centre, known for its beaches and vibrant nightlife.",
  "The muscular system enables movement, maintains posture, and generates heat through the contraction of muscle fibres.",
  "The city of San Francisco is built on hills and is famous for the Golden Gate Bridge and its tech industry.",
  "Robotics combines engineering, computer science, and artificial intelligence to design and build automated machines.",
  "The city of Melbourne is known for its coffee culture, street art, and hosting major sporting events like the Australian Open.",
  "The lymphatic system helps maintain fluid balance and plays a crucial role in the body's immune response.",
  "The city of Hong Kong is a major international financial centre and one of the world's busiest container ports.",
  "Gene therapy involves introducing genetic material into a patient's cells to treat or prevent disease.",
  "The city of Vancouver is surrounded by mountains and ocean, making it one of the most scenic cities in North America.",
  "The urinary system filters waste products from the blood and maintains water and electrolyte balance in the body.",
  "The city of Copenhagen is the capital of Denmark and known for its bicycle-friendly infrastructure and sustainable living.",
  "Stem cell research studies undifferentiated cells that have the potential to develop into many different cell types.",
  "The city of Madrid is the capital of Spain and home to world-renowned art museums like the Prado and Reina Sofía.",
  "The reproductive system enables the production of offspring through the creation and fusion of gametes.",
  "The city of Seoul is the capital of South Korea and a global centre for technology, fashion, and entertainment.",
  "Bioinformatics combines computer science, statistics, and biology to analyse and interpret biological data.",
  "The city of Berlin is the capital of Germany and has a rich history spanning from medieval times to modern reunification.",
  "The integumentary system, including skin, hair, and nails, provides protection and helps regulate body temperature.",
  "The city of Toronto is Canada's largest city and a major centre for finance, arts, and culture.",
  "Pharmacology studies how drugs interact with biological systems to produce therapeutic or toxic effects.",
  "The city of Warsaw is the capital of Poland and has been rebuilt after extensive destruction during World War II.",
  "The sensory system processes information from the environment through specialised organs like eyes, ears, and skin.",
  "The city of Istanbul has served as the capital of three successive empires: Roman, Byzantine, and Ottoman.",
  "Epidemiology studies the distribution and determinants of health and disease in populations.",
  "The city of Johannesburg is South Africa's largest city and the economic hub of the African continent.",
  "The excretory system removes metabolic waste products from the body to maintain homeostasis.",
  "The city of Bangalore is known as India's Silicon Valley due to its thriving information technology industry.",
  "Immunology studies the immune system and how it protects the body from pathogens and foreign substances.",
  "The city of Casablanca is Morocco's largest city and economic centre, immortalised in classic Hollywood cinema.",
  "The cardiovascular system transports oxygen, nutrients, and waste products throughout the body via blood circulation.",
  "The city of Lagos is Nigeria's largest city and one of the fastest-growing urban areas in the world.",
  "Microbiology studies microscopic organisms including bacteria, viruses, fungi, and parasites.",
  "The city of Karachi is Pakistan's largest city and serves as the country's economic and financial centre.",
  "The endocrine system coordinates long-term changes in the body through chemical messengers called hormones.",
  "The city of Lima is the capital of Peru and was once the centre of the Spanish colonial empire in South America.",
  "Pathology studies the causes and effects of diseases through examination of organs, tissues, and cells.",
  "The city of Dhaka is the capital of Bangladesh and one of the most densely populated cities in the world.",
  "The nervous system processes sensory information and coordinates responses through electrical and chemical signals.",
  "The city of Tehran is the capital of Iran and the country's political, cultural, and economic centre.",
  "Anatomy studies the structure and organisation of living organisms and their parts.",
  "The city of Riyadh is the capital of Saudi Arabia and the centre of the country's government and economy.",
  "Physiology examines how living organisms and their parts function at the molecular, cellular, and system levels.",
  "The city of Bogotá is the capital of Colombia and is situated on a high plateau in the Andes Mountains.",
  "Biochemistry studies chemical processes and substances that occur within living organisms.",
  "The city of Kuala Lumpur is the capital of Malaysia and famous for the Petronas Twin Towers.",
  "Cell biology examines the structure, function, and behaviour of cells, the basic units of life.",
  "The city of Addis Ababa is the capital of Ethiopia and serves as the diplomatic capital of Africa.",
  "Molecular biology studies biological activity at the molecular level, including DNA, RNA, and proteins.",
  "The city of Nairobi is the capital of Kenya and a major centre for business and culture in East Africa.",
  "Genetics examines heredity and the variation of inherited characteristics in living organisms.",
  "The city of Accra is the capital of Ghana and serves as the country's economic and administrative centre.",
  "Developmental biology studies how organisms grow and develop from fertilisation to maturity.",
  "The city of Dakar is the capital of Senegal and the westernmost city on the African continent.",
  "Ecology studies the relationships between organisms and their environment at various levels of organisation.",
  "The city of Tunis is the capital of Tunisia and has been an important city since ancient Carthaginian times.",
  "Evolutionary biology examines the processes that have shaped the diversity of life on Earth over time.",
  "The city of Algiers is the capital of Algeria and is known as the 'White City' due to its whitewashed buildings.",
  "Marine biology studies life in oceans and other saltwater environments, including coral reefs and deep-sea habitats.",
  "The city of Rabat is the capital of Morocco and is located on the Atlantic coast at the mouth of the Bou Regreg river.",
  "Botany studies plant life, including their structure, growth, reproduction, metabolism, and classification.",
  "The city of Khartoum is the capital of Sudan and is located at the confluence of the Blue and White Nile rivers.",
  "Zoology studies animal life, including their behaviour, structure, physiology, classification, and distribution.",
  "The city of Kampala is the capital of Uganda and is built on seven hills near Lake Victoria.",
  "Ornithology is the branch of zoology that studies birds, including their behaviour, ecology, and evolution.",
  "The city of Kigali is the capital of Rwanda and has been rebuilt as a model of urban planning and cleanliness.",
  "Entomology studies insects, which represent the largest group of animals on Earth in terms of species diversity.",
  "The city of Antananarivo is the capital of Madagascar, an island nation known for its unique biodiversity.",
  "Ichthyology studies fish, including their anatomy, behaviour, classification, and ecological relationships.",
  "The city of Port Louis is the capital of Mauritius, an island nation in the Indian Ocean.",
  "Herpetology studies reptiles and amphibians, including snakes, lizards, turtles, frogs, and salamanders.",
  "The city of Victoria is the capital of Seychelles, an archipelago of islands in the Indian Ocean.",
  "Mammalogy studies mammals, including their anatomy, behaviour, ecology, and evolutionary relationships.",
  "The city of Moroni is the capital of the Comoros, a volcanic archipelago in the Indian Ocean.",
  "Primatology studies primates, including humans, apes, monkeys, and prosimians.",
  "The city of Djibouti is the capital of Djibouti and serves as an important port in the Horn of Africa.",
  "Paleontology studies fossils to understand the history of life on Earth and evolutionary processes.",
  "The city of Asmara is the capital of Eritrea and is known for its well-preserved Italian colonial architecture.",
  "Astrobiology studies the possibility of life beyond Earth and the conditions necessary for life to exist.",
  "The city of Mogadishu is the capital of Somalia and has been an important trading port for centuries.",
  "Biophysics applies physical principles and methods to understand biological systems and phenomena.",
  "The city of N'Djamena is the capital of Chad and is located at the confluence of the Chari and Logone rivers.",
  "Structural biology studies the molecular structure of biological macromolecules and how they relate to function.",
  "The city of Bangui is the capital of the Central African Republic and is located on the Ubangi River.",
  "Systems biology studies complex interactions within biological systems using computational and mathematical approaches.",
  "The city of Libreville is the capital of Gabon and is located on the coast of west central Africa.",
  "Computational biology uses mathematical models and computational techniques to study biological systems.",
  "The city of Malabo is the capital of Equatorial Guinea and is located on the island of Bioko.",
  "Conservation biology focuses on protecting biodiversity and managing natural resources sustainably.",
  "The city of São Tomé is the capital of São Tomé and Príncipe, an island nation in the Gulf of Guinea.",
  "Synthetic biology combines engineering principles with biology to design and construct new biological parts and systems.",
  "The city of Luanda is the capital of Angola and one of the fastest-growing cities in Africa.",
  "Forensic biology applies biological techniques to legal investigations, including DNA analysis and species identification.",
  "The city of Kinshasa is the capital of the Democratic Republic of the Congo and one of the largest cities in Africa.",
  "Agricultural biology studies crop plants and livestock to improve food production and farming practices.",
  "The city of Brazzaville is the capital of the Republic of the Congo and is located on the Congo River.",
  "Environmental biology examines how organisms interact with their environment and respond to environmental changes.",
  "The city of Yaoundé is the capital of Cameroon and is known as the 'City of Seven Hills'.",
  "Toxicology studies the adverse effects of chemicals on living organisms and the environment.",
  "The city of Abuja is the capital of Nigeria and was built in the 1980s to replace Lagos as the capital.",
  "Neurobiology studies the nervous system, including the brain, spinal cord, and peripheral nerves.",
  "The city of Niamey is the capital of Niger and is located on the Niger River in West Africa.",
  "Developmental neurobiology examines how the nervous system develops from embryonic stages to maturity.",
  "The city of Ouagadougou is the capital of Burkina Faso and is the country's largest city.",
  "Cognitive neuroscience studies the biological processes underlying cognition and behaviour.",
  "The city of Bamako is the capital of Mali and is located on the Niger River in West Africa.",
  "Behavioural neuroscience examines the biological basis of behaviour and mental processes.",
  "The city of Conakry is the capital of Guinea and is located on the Atlantic coast of West Africa.",
  "Social neuroscience studies how biological systems implement social processes and behaviour.",
  "The city of Freetown is the capital of Sierra Leone and was founded as a settlement for freed slaves.",
  "Neuroplasticity refers to the brain's ability to reorganise and form new neural connections throughout life.",
  "The city of Monrovia is the capital of Liberia and was named after U.S. President James Monroe.",
  "Neurodegeneration studies the progressive loss of structure or function of neurons in diseases like Alzheimer's.",
  "The city of Banjul is the capital of The Gambia and is located on an island at the mouth of the Gambia River.",
  "Neuroinflammation involves the activation of immune cells in the brain and central nervous system.",
  "The city of Bissau is the capital of Guinea-Bissau and is located on the Geba River estuary.",
  "Neuromodulation refers to the alteration of nerve activity through targeted delivery of stimuli.",
  "The city of Praia is the capital of Cape Verde, an island nation off the west coast of Africa.",
  "Neurogenesis is the process by which new neurons are formed in the brain throughout life.",
  "The city of Las Palmas is the largest city in the Canary Islands and a major tourist destination.",
  "Synaptic plasticity refers to changes in the strength of connections between neurons.",
  "The city of Santa Cruz de Tenerife is the capital of Tenerife in the Canary Islands.",
  "Neurochemistry studies the chemical processes and substances that occur in the nervous system.",
  "The city of Palma is the capital of Mallorca in the Balearic Islands and a popular Mediterranean destination.",
  "Neurophysiology examines the function of the nervous system at the cellular and molecular level.",
  "The city of Ibiza is famous for its vibrant nightlife and electronic music scene in the Mediterranean.",
  "Neuroanatomy studies the structure and organisation of the nervous system.",
  "The city of Mahón is the capital of Menorca, known for its natural harbour and prehistoric monuments.",
  "Neuroethology studies the neural basis of natural animal behaviour.",
  "The city of Formentera is the smallest of Spain's Balearic Islands and known for its pristine beaches.",
  "Computational neuroscience uses mathematical models to study brain function and neural processes.",
  "The city of Gibraltar is a British territory located at the southern tip of the Iberian Peninsula.",
  "Neural networks are computing systems inspired by biological neural networks in animal brains.",
  "The city of Andorra la Vella is the capital of Andorra, a microstate in the Pyrenees mountains.",
  "Artificial neural networks are machine learning models inspired by the structure of biological neurons.",
  "The city of Monaco is a city-state known for its casinos, luxury lifestyle, and Formula One Grand Prix.",
  "Deep learning uses artificial neural networks with multiple layers to model complex patterns in data.",
  "The city of San Marino is the capital of San Marino, one of the world's smallest republics.",
  "Convolutional neural networks are particularly effective for image recognition and computer vision tasks.",
  "The city of Vatican City is the smallest sovereign state in the world and the spiritual centre of Catholicism.",
  "Recurrent neural networks can process sequential data and are used in natural language processing.",
  "The city of Vaduz is the capital of Liechtenstein, a small principality in the Alps.",
  "Reinforcement learning enables machines to learn optimal behaviour through trial and error.",
  "The city of Luxembourg is the capital of Luxembourg and a major financial centre in Europe.",
  "Natural language processing enables computers to understand, interpret, and generate human language.",
  "The city of Brussels is the capital of Belgium and hosts the headquarters of the European Union.",
  "Computer vision enables machines to identify and analyse visual content from images and videos.",
  "The city of Bern is the capital of Switzerland and is known for its medieval architecture.",
  "Speech recognition technology converts spoken language into text using machine learning algorithms.",
  "The city of Vienna is the capital of Austria and was once the centre of the Habsburg Empire.",
  "Autonomous vehicles use artificial intelligence to navigate and make driving decisions without human intervention.",
  "The city of Prague is the capital of the Czech Republic and is famous for its historic architecture.",
  "Expert systems are AI programs that emulate the decision-making ability of human experts in specific domains.",
  "The city of Bratislava is the capital of Slovakia and is located on the Danube River.",
  "Fuzzy logic is a form of many-valued logic that deals with reasoning that is approximate rather than fixed.",
  "The city of Ljubljana is the capital of Slovenia and is known for its university and baroque architecture.",
  "Genetic algorithms are optimisation techniques inspired by the process of natural selection.",
  "The city of Zagreb is the capital of Croatia and the country's political, cultural, and economic centre.",
  "Swarm intelligence studies collective behaviour of decentralised, self-organised systems.",
  "The city of Sarajevo is the capital of Bosnia and Herzegovina and hosted the 1984 Winter Olympics.",
  "Evolutionary computation uses mechanisms inspired by biological evolution to solve optimisation problems.",
  "The city of Podgorica is the capital of Montenegro and is located at the confluence of the Ribnica and Morača rivers.",
  "Quantum computing harnesses quantum mechanical phenomena to process information in fundamentally new ways.",
  "The city of Skopje is the capital of North Macedonia and is known for its diverse architectural styles.",
  "Biometric authentication uses unique biological characteristics to verify individual identity.",
  "The city of Tirana is the capital of Albania and the country's largest city and economic centre.",
  "Cybersecurity protects digital systems, networks, and data from cyber threats and attacks.",
  "The city of Pristina is the capital of Kosovo and the country's economic and cultural centre.",
  "Internet of Things connects everyday objects to the internet, enabling them to send and receive data.",
  "The city of Belgrade is the capital of Serbia and is located at the confluence of the Sava and Danube rivers.",
  "Cloud computing delivers computing services over the internet on a pay-as-you-use basis.",
  "The city of Bucharest is the capital of Romania and the country's largest city and industrial centre.",
  "Big data analytics processes large volumes of data to uncover patterns and insights for decision-making.",
  "The city of Sofia is the capital of Bulgaria and is located in the Sofia Valley at the foot of Vitosha mountain.",
  "Edge computing brings computation and data storage closer to the sources of data to reduce latency.",
];
